### ISSUE TITLE
Submission rejected for copyrights

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/RCSF#7]
@jianboqi  Email received after submission.

> Thanks, we see:
> 
> you state in te DESCRIPTION file
> 
> ```
> Authors@R: c(
>      person("Jean-Romain", "Roussel", email =
> "jean-romain.roussel.1@ulaval.ca", role = c("aut", "cre", "cph")),
>      person("Jianbo", "Qi", email = "jianboqi@gmail.com", role =
> c("aut", "cph")))
> ```
> 
> but in your C source files we see, e.g.:
> 
> ```
> // Copyright 2017 State Key Laboratory of Remote Sensing Science,
> // Institute of Remote Sensing Science and Engineering, Beijing Normal University
> // #    Wuming Zhang; Jianbo Qi; Peng Wan; Hongtao Wang
> // #
> // #    contact us: 2009zwm@gmail.com; wpqjbzwm@126.com
> // #
>  ```
>
> So you failed to add the copyright holder "State Key Laboratory of
> Remote Sensing Science, Institute of Remote Sensing Science and
> Engineering, Beijing Normal University" anbd possibly others.
> 
> Please declare all authors, contributors and copyright holders.
> 
> Please fix and resubmit.
> 
> Best,
> Uwe Ligges

Please list me all the copyright holders that must be added.

Thanks

**Comment by Jean-Romain** [comment]
```
Authors@R: c(
     person("Jean-Romain", "Roussel", email = "jean-romain.roussel.1@ulaval.ca", role = c("aut", "cre", cph")),
     person("Jianbo", "Qi", email = "jianboqi@gmail.com", role = c("aut", "cph")),
     person("Wuming", "Zhang", email = "", role = c("cph")),
     person("Peng", "Wan", email = "", role = c( "cph")),
     person("Hongtao", "Wang", email = "", role = c("cph")),
     person("State Key Laboratory of Remote Sensing Science", role = c("cph")))
```

- `cph` means copyright holder
- `aut` means author. It is the person who made the package. You are an author but what about the other collaborators?
- `cre` means creator. It is the person who maintains the package. It is me only.

Does this seem correct? Who is/are actually the copyrigth holders? Does your university hold the copyright? Do you hold the copyright? What about other persons? Does your university allows for sharing the code if it holds the copyright. Who actually wrote the code?

**Comment by jianboqi** [comment]
Hello Jean-Romain,
  Thank you very much for your efforts to submit the package. This seems correct. the last cph could be "State Key Laboratory of Remote Sensing Science, Institute of Remote Sensing Science and Engineering, Beijing Normal University".
  This code is actually written by myself. We can share it as public. This four authors are enough.

**Comment by Jean-Romain** [comment]
> This four authors are enough

You said "authors"... If the code is written by you, the other person are not copyright holders? Right? Is it important to make the distinction between copyright holders and author and contributors. They have different meaning. I guess the other persons are your superiors and/or supervisors. Copyright holders can claim rights on the code. So I need to be sure of the roles. There are 5 tags to my knowledge:

- `cre`
- `cph`
- `aut`
- `ctb`: contributor
- `fnd`: funding

The copyright holders tag have a legal basis so we must be sure of its content. For your university it is explicitly written is the file so no choice. But we must be sure of the status of the others and it is likely to be defined in the agreement you passed with you employer (the university and/or your superiors). It can be any combination of 1 to 4 of theses tags but the maintainer tag (cre) is reserved to me.

I is a bit annoying but it must be chosen carefully because it is important.

**Comment by Jean-Romain** [comment]
Also it is important to consider that:

> Every package must have at least one author (aut) and one maintainer (cre) (they might be the same person). The creator must have an email address. These fields are used to generate the basic citation for the package (e.g. citation("pkgname")). Only people listed as **authors** will be included in the auto-generated citation 

For example:

```r
citation("lidR")
```

gives
 
```
  Jean-Romain Roussel and David Auty (2018). lidR: Airborne LiDAR Data
  Manipulation and Visualization for Forestry Applications. R package
  version 2.0.0. https://github.com/Jean-Romain/lidR

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {lidR: Airborne LiDAR Data Manipulation and Visualization for Forestry
Applications},
    author = {Jean-Romain Roussel and David Auty},
    year = {2018},
    note = {R package version 2.0.0},
    url = {https://github.com/Jean-Romain/lidR},
  }
```

For RCSF it gives 

```
  Jean-Romain Roussel and Jianbo Qi (2018). RCSF: Airborne LiDAR
  Filtering Method Based on Cloth Simulation. R package version 1.0.0.
```

Notice that it is not mandatory for me to be an author. I can only be the creator i.e. the maintainer.
