### ISSUE TITLE
CSF not working

### ISSUE THREAD

**Issue by spono** [Jean-Romain/RCSF#8]
Ciao JR,
I'm running CSF from lidR `lidR 2.1.3` but with no success.
I'm applying it on a pretty simple point cloud (150 hectares of flat land, appr. 2.5 million pts) it takes eternity to compute & requires up to 5gb RAM.
The same cloud is managed in only few mins with `pmf()`.

Code is definitely the most basic one:
```r
las = readLAS(lasfile)
las = lasground(las, csf() )
```

I tested a bit more on another cloud (11Mln pts) and it works, so it might be a specific issue of the one I'm using. I tried the CSF implemented in CloudCompare and the results are the same.

I sent you the pointcloud by email.

**Comment by Jean-Romain** [comment]
So you are saying that you run out of memory only for this point cloud and both in lidR and CloudCompare. Right? If yes you should report this to @jianboqi  in https://github.com/jianboqi/CSF

I tested myself and the amount of memory increased a lot and I get stucked in a infinite loop. I tested on another file of mine (with half the number of points) and it ran smoothly.

I also tried by removing duplicated points: same issue.

**Comment by spono** [comment]
oh ok, I'll write on the other repo.
thanks again for further testing and sorry for taking your time!

**Comment by Jean-Romain** [comment]
No problem. Anyway if @jianboqi  find the issue I will have to integrate  the fix in the package.

**Comment by spono** [comment]
I'll let you know as soon as I get a reply!
