### ISSUE TITLE
Composite cloth resolution (quilts?)

### ISSUE THREAD

**Issue by mosscoder** [Jean-Romain/RCSF#9]
Greetings, I have been exploring the use of the CSF algorithm to classify ground and canopy points in a SfM point cloud with lidR pacakge. My ROI contains both forest and shrubland plant communities. Some of the shrubs are visually apparent in my point cloud, and I'd like to try and classify shrub canopy. I've found that the default cloth resolution of 0.5m is suitable for tree detection when the canopy is not overly dense, but this default setting does not usually pick up on shrubs. I've tried a grid search of the CSF tuning parameters to improve the shrub detection capacity of this framework, and found that the most relevant parameter is resolution of the cloth, and it becomes more sensitive to shrubs somewhere between 2 and 2.5m. The problem with such a coarse cloth is its lack of specificity, and ground points are classified as canopy in topographically complex areas. Still, in flatter regions a coarse cloth can perform well. I'm presently exploring how terrain conditions correlate with accuracy of cloth resolution, focusing on regions of my ROI where 0.5 and 2 meter cloth classifiers disagree. I'm wondering if you are aware of any other efforts to vary cloth resolution based upon terrain conditions with the goal of coming up with, perhaps, rules or cutoffs to create a mosaic composed of multiple cloth models.

**Comment by Jean-Romain** [comment]
RCSF is just a wrapper around the code of CSF. If you have any question please ask to @jianboqi in https://github.com/jianboqi/CSF. He knows his code better than me. Regards.
